[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "MSGS",
    "SRVS",
    "ACTIONS",
    "FIRSTPARTY",
    "LOCALFOLDER",
    "TYPING",
]
default_section = "THIRDPARTY"
known_msgs = ["*.msg"]
known_srvs = ["*.srv"]
known_actions = ["*.action"]
known_typing = ["typing", "mypy_extensions", "typing_extensions"]
force_sort_within_sections = "true"
force_to_top = "true"
src_paths = ["ros/**"]
